### PR TITLE
argument $masks in find methods made required

### PR DESCRIPTION
**Pull request by vlastavesely**
- bug fix? yes
- BC break? no

### CODE REVIEW

**Comment by dg** [comment]
I like more explicit findFiles('*')

**Comment by vlastavesely** [comment]
OK, but, in my opinion, it is problem that if you call it with empty `$masks`, you get notice `Undefined offset: 0 in` instead of something more meaningful.

**Comment by dg** [comment]
And can you fix it?

**Comment by vlastavesely** [comment]
yes

**Comment by vlastavesely** [comment]
Argument $masks is now required. Do you like it more?

**Comment by dg** [comment]
What about to change declaration to `findFiles($mask, ...$masks)`, ie. native enforce first parameter.

**Comment by dg** [comment]
And perhaps use only one way: the array or more parameters. The second way should be deprecated.

**Comment by vlastavesely** [comment]
> What about to change declaration to findFiles($mask, ...$masks), ie. native enforce first parameter?

I think it would be unnecessarily overcombined and little bit confusing.

**Comment by vlastavesely** [comment]
What about to unify API of Finder and RobotLoader in some way? RobotLoader accepts `array` or comma separated string while Finder accepts `array` or argument list. I like the `array|string` version or only `array` eventually.

**Comment by JanTvrdik** [comment]
It may be just me, but I would prefer that calling `findFiles()` without arguments was allowed and always resulted in finding nothing.

**Comment by vlastavesely** [comment]
I can imagine I would be a little bit confused if function named `find()` returned nothing and did not throw any warning or error.

**Comment by Majkl578** [comment]
> and always resulted in finding nothing

And someone might expect the opposite, find all files.

**Comment by f3l1x** [comment]
I agree with @Majkl578 and also with @JanTvrdik.

`findFiles` can be understood as `find-all` as well as `find-nothing`. What about clarify to `findFiles()->all()`,`allFiles`, `findFiles(Finder::ALL)`. Also we could require at least one argument to findFiles. 

Just an idea, let's discuss it.

**Comment by vlastavesely** [comment]
According to me, function that does not find anything by default is useless.

Take Linux command `find` for example. Does not matter whether you run it by `find` or `find .`. It always finds all files in the directory unless you limit it by some pattern.

Another thing: imagine you have a directory and you want to check whether it is empty. You call `Finder::findFiles()`, it finds nothing and you remove the directory with confidence. But it contained important files you did not back up... You lost your files only because you forget to specify pattern when finding files...

**Comment by enumag** [comment]
I also think findFiles without any mask should return all files. It makes more sense then returning nothing and is consistent with similar tools.

**Comment by f3l1x** [comment]
Thanks @dg

**Pull request closed without merging**
